package com.prima.factory.controller;
import java.util.*; import org.springframework.web.bind.annotation.*; import com.prima.factory.dto.ApiResponse; import com.prima.factory.service.MonitoringService;
@RestController @RequestMapping("/api/v1") public class MonitoringController { private final MonitoringService s; public MonitoringController(MonitoringService s){this.s=s;}
 @GetMapping("/factories") ApiResponse<?> factories(){return ApiResponse.ok(s.mapper().factories());} @GetMapping("/lines") ApiResponse<?> lines(){return ApiResponse.ok(s.mapper().lines());}
 @GetMapping("/dashboard/summary") ApiResponse<?> dashboard(){return ApiResponse.ok(s.dashboard());} @GetMapping("/realtime/equipment") ApiResponse<?> equipment(){return ApiResponse.ok(s.equipment());}
 @GetMapping("/realtime/equipment/{id}") ApiResponse<?> equipment(@PathVariable long id){return ApiResponse.ok(s.mapper().equipment(id));} @GetMapping("/realtime/equipment/{id}/trend") ApiResponse<?> trend(@PathVariable long id){return ApiResponse.ok(s.mapper().trend(id,60));}
 @GetMapping("/equipment") ApiResponse<?> equipmentList(){return ApiResponse.ok(s.equipment());} @PostMapping("/equipment") ApiResponse<?> equipmentCreate(@RequestBody Map<String,Object>b){s.createEquipment(b);return ApiResponse.ok(b);} @PutMapping("/equipment/{id}") ApiResponse<?> equipmentUpdate(@PathVariable long id,@RequestBody Map<String,Object>b){s.updateEquipment(id,b);return ApiResponse.ok(b);}@PatchMapping("/equipment/{id}/deactivate") ApiResponse<?> equipmentDeactivate(@PathVariable long id){s.deactivateEquipment(id);return ApiResponse.ok(Map.of("id",id,"active",false));}
 @GetMapping("/products") ApiResponse<?> products(){return ApiResponse.ok(s.products());} @PostMapping("/products") ApiResponse<?> productCreate(@RequestBody Map<String,Object>b){s.mapper().insertProduct(b);return ApiResponse.ok(b);}@PutMapping("/products/{id}") ApiResponse<?> productUpdate(@PathVariable long id,@RequestBody Map<String,Object>b){s.mapper().updateProduct(id,b);return ApiResponse.ok(b);}@PatchMapping("/products/{id}/deactivate") ApiResponse<?> productDeactivate(@PathVariable long id){s.mapper().deactivateProduct(id);return ApiResponse.ok(Map.of("id",id,"active",false));}
 @GetMapping("/analytics/production") ApiResponse<?> production(){return ApiResponse.ok(s.mapper().productionAnalytics());}@GetMapping("/analytics/downtime") ApiResponse<?> downtime(){return ApiResponse.ok(s.mapper().downtimeAnalytics());}@GetMapping("/analytics/bottleneck") ApiResponse<?> bottleneck(){return ApiResponse.ok(s.mapper().downtimeAnalytics());}@GetMapping("/analytics/alarms") ApiResponse<?> alarms(){return ApiResponse.ok(s.mapper().alarms());}@GetMapping("/maintenance") ApiResponse<?> maintenance(){return ApiResponse.ok(s.mapper().maintenance());}@GetMapping("/system/collection-health") ApiResponse<?> collection(){return ApiResponse.ok(s.collection());}@GetMapping("/system/health-summary") ApiResponse<?> health(){return ApiResponse.ok(Map.of("services",List.of("BACKEND","DEVICE_SERVER","MYSQL")));}
}
