-- DEVELOPMENT RESET DUMP. Drops ONLY prima_factory_360.
DROP DATABASE IF EXISTS prima_factory_360;
CREATE DATABASE prima_factory_360 CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE prima_factory_360;
-- PRIMA FACTORY 360 schema source of truth. MySQL Community 8.x / UTC storage.
CREATE TABLE factory(id BIGINT AUTO_INCREMENT PRIMARY KEY,factory_code VARCHAR(30) NOT NULL UNIQUE,factory_name VARCHAR(100) NOT NULL,location VARCHAR(255),timezone VARCHAR(50) NOT NULL DEFAULT 'Asia/Seoul',is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)) ENGINE=InnoDB;
CREATE TABLE production_line(id BIGINT AUTO_INCREMENT PRIMARY KEY,factory_id BIGINT NOT NULL,line_code VARCHAR(30) NOT NULL,line_name VARCHAR(100) NOT NULL,display_order INT NOT NULL,is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),UNIQUE(factory_id,line_code),FOREIGN KEY(factory_id) REFERENCES factory(id)) ENGINE=InnoDB;
CREATE TABLE equipment(id BIGINT AUTO_INCREMENT PRIMARY KEY,line_id BIGINT NOT NULL,equipment_code VARCHAR(30) NOT NULL UNIQUE,equipment_name VARCHAR(100) NOT NULL,equipment_type ENUM('ROBOT','PRESS','OTHER') NOT NULL,manufacturer VARCHAR(80),model VARCHAR(80),serial_number VARCHAR(80),process_order INT NOT NULL DEFAULT 0,installed_date DATE,is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),INDEX(line_id,is_active),FOREIGN KEY(line_id) REFERENCES production_line(id)) ENGINE=InnoDB;
CREATE TABLE equipment_connection(id BIGINT AUTO_INCREMENT PRIMARY KEY,equipment_id BIGINT NOT NULL UNIQUE,protocol ENUM('MC_TCP','MC_UDP','MODBUS_TCP','SIMULATOR') NOT NULL,ip_address VARCHAR(45),port INT,network_number INT,pc_number INT,station_number INT,timeout_ms INT DEFAULT 1000,retry_count INT DEFAULT 3,collection_interval_ms INT DEFAULT 1000,byte_order VARCHAR(20) DEFAULT 'BIG_ENDIAN',is_read_only BOOLEAN NOT NULL DEFAULT TRUE,is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),FOREIGN KEY(equipment_id) REFERENCES equipment(id)) ENGINE=InnoDB;
CREATE TABLE equipment_tag_mapping(id BIGINT AUTO_INCREMENT PRIMARY KEY,equipment_id BIGINT NOT NULL,logical_tag_name VARCHAR(100) NOT NULL,device_type VARCHAR(30),device_address VARCHAR(50) NOT NULL,data_type VARCHAR(30) NOT NULL,word_count INT DEFAULT 1,scale_value DECIMAL(12,4) DEFAULT 1,offset_value DECIMAL(12,4) DEFAULT 0,unit VARCHAR(20),min_value DECIMAL(18,4),max_value DECIMAL(18,4),is_active BOOLEAN DEFAULT TRUE,created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),UNIQUE(equipment_id,logical_tag_name),FOREIGN KEY(equipment_id) REFERENCES equipment(id)) ENGINE=InnoDB;
CREATE TABLE product(id BIGINT AUTO_INCREMENT PRIMARY KEY,product_code VARCHAR(40) NOT NULL UNIQUE,product_name VARCHAR(120) NOT NULL,vehicle_model VARCHAR(100),customer VARCHAR(100),specification VARCHAR(255),unit VARCHAR(20) DEFAULT 'EA',image_path VARCHAR(255),is_active BOOLEAN DEFAULT TRUE,remarks TEXT,created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)) ENGINE=InnoDB;
CREATE TABLE product_line_standard(id BIGINT AUTO_INCREMENT PRIMARY KEY,product_id BIGINT NOT NULL,factory_id BIGINT NOT NULL,line_id BIGINT NOT NULL,equipment_id BIGINT,standard_cycle_time DECIMAL(10,3) NOT NULL,hourly_rate DECIMAL(10,2) NOT NULL,standard_spm DECIMAL(8,2),target_uptime_rate DECIMAL(5,2),default_target_quantity INT,mold_number VARCHAR(50),process_order INT,quality_linked BOOLEAN DEFAULT FALSE,created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),UNIQUE(product_id,line_id,equipment_id),FOREIGN KEY(product_id) REFERENCES product(id),FOREIGN KEY(factory_id) REFERENCES factory(id),FOREIGN KEY(line_id) REFERENCES production_line(id),FOREIGN KEY(equipment_id) REFERENCES equipment(id)) ENGINE=InnoDB;
CREATE TABLE production_plan(id BIGINT AUTO_INCREMENT PRIMARY KEY,work_order_number VARCHAR(50) NOT NULL UNIQUE,production_date DATE NOT NULL,factory_id BIGINT NOT NULL,line_id BIGINT NOT NULL,equipment_id BIGINT,product_id BIGINT NOT NULL,target_quantity INT NOT NULL,standard_cycle_time DECIMAL(10,3),standard_hourly_rate DECIMAL(10,2),planned_start_at DATETIME(3),planned_end_at DATETIME(3),shift_code VARCHAR(20),planned_minutes INT,status VARCHAR(30),created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),INDEX(production_date,line_id),FOREIGN KEY(factory_id) REFERENCES factory(id),FOREIGN KEY(line_id) REFERENCES production_line(id),FOREIGN KEY(equipment_id) REFERENCES equipment(id),FOREIGN KEY(product_id) REFERENCES product(id)) ENGINE=InnoDB;
CREATE TABLE robot_telemetry(id BIGINT AUTO_INCREMENT PRIMARY KEY,equipment_id BIGINT NOT NULL,line_id BIGINT NOT NULL,collected_at DATETIME(3) NOT NULL,source_timestamp DATETIME(3),collection_success BOOLEAN NOT NULL,data_quality ENUM('GOOD','UNCERTAIN','BAD') NOT NULL,last_good_received_at DATETIME(3),response_ms INT,operating_mode VARCHAR(20),operating_status VARCHAR(30),current_program VARCHAR(100),cycle_started BOOLEAN DEFAULT FALSE,cycle_completed BOOLEAN DEFAULT FALSE,cycle_count BIGINT,cycle_time DECIMAL(10,3),servo_on BOOLEAN,motor_current DECIMAL(10,3),load_rate DECIMAL(6,2),temperature DECIMAL(6,2),emergency_stop BOOLEAN DEFAULT FALSE,safety_door_closed BOOLEAN,alarm_code VARCHAR(40),alarm_message VARCHAR(255),press_ready BOOLEAN,robot_ready BOOLEAN,material_detected BOOLEAN,transfer_completed BOOLEAN,total_runtime_minutes BIGINT,created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),INDEX idx_robot_time(equipment_id,collected_at),FOREIGN KEY(equipment_id) REFERENCES equipment(id),FOREIGN KEY(line_id) REFERENCES production_line(id)) ENGINE=InnoDB;
CREATE TABLE press_telemetry(id BIGINT AUTO_INCREMENT PRIMARY KEY,equipment_id BIGINT NOT NULL,line_id BIGINT NOT NULL,collected_at DATETIME(3) NOT NULL,source_timestamp DATETIME(3),collection_success BOOLEAN NOT NULL,data_quality ENUM('GOOD','UNCERTAIN','BAD') NOT NULL,last_good_received_at DATETIME(3),response_ms INT,operating_status VARCHAR(30),auto_mode BOOLEAN,ready_signal BOOLEAN,run_signal BOOLEAN,stop_signal BOOLEAN,alarm_signal BOOLEAN,production_counter BIGINT,spm DECIMAL(8,3),press_angle DECIMAL(8,3),load_ton DECIMAL(10,3),slide_position DECIMAL(10,3),motor_on BOOLEAN,temperature DECIMAL(6,2),safety_ok BOOLEAN,interlock_ok BOOLEAN,mold_number VARCHAR(50),product_code VARCHAR(40),error_number VARCHAR(40),digital_inputs JSON,digital_outputs JSON,created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),INDEX idx_press_time(equipment_id,collected_at),FOREIGN KEY(equipment_id) REFERENCES equipment(id),FOREIGN KEY(line_id) REFERENCES production_line(id)) ENGINE=InnoDB;
CREATE TABLE equipment_current_state(equipment_id BIGINT PRIMARY KEY,operating_status VARCHAR(30) NOT NULL,communication_status ENUM('CONNECTED','DEGRADED','DISCONNECTED') NOT NULL,display_status VARCHAR(30) NOT NULL,status_started_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),production_count BIGINT DEFAULT 0,cycle_time DECIMAL(10,3),load_rate DECIMAL(6,2),current_amp DECIMAL(10,3),temperature DECIMAL(6,2),current_alarm VARCHAR(255),response_ms INT,last_good_received_at DATETIME(3),collected_at DATETIME(3) NOT NULL,updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),INDEX(display_status,collected_at),FOREIGN KEY(equipment_id) REFERENCES equipment(id)) ENGINE=InnoDB;
CREATE TABLE equipment_state_event(id BIGINT AUTO_INCREMENT PRIMARY KEY,equipment_id BIGINT NOT NULL,started_at DATETIME(3) NOT NULL,ended_at DATETIME(3),duration_seconds INT,automatic_status VARCHAR(30) NOT NULL,corrected_status VARCHAR(30),corrected_by BIGINT,corrected_at DATETIME(3),created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),INDEX(equipment_id,started_at),FOREIGN KEY(equipment_id) REFERENCES equipment(id)) ENGINE=InnoDB;
CREATE TABLE production_count_event(id BIGINT AUTO_INCREMENT PRIMARY KEY,equipment_id BIGINT NOT NULL,source_event_key VARCHAR(100) NOT NULL UNIQUE,event_at DATETIME(3) NOT NULL,quantity_delta INT NOT NULL,cumulative_count BIGINT NOT NULL,created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),INDEX(equipment_id,event_at),FOREIGN KEY(equipment_id) REFERENCES equipment(id)) ENGINE=InnoDB;
CREATE TABLE alarm_event(id BIGINT AUTO_INCREMENT PRIMARY KEY,equipment_id BIGINT NOT NULL,alarm_code VARCHAR(40) NOT NULL,alarm_message VARCHAR(255),occurred_at DATETIME(3) NOT NULL,cleared_at DATETIME(3),duration_seconds INT,severity VARCHAR(20),occurrence_count INT DEFAULT 1,is_acknowledged BOOLEAN DEFAULT FALSE,created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),INDEX(equipment_id,occurred_at),FOREIGN KEY(equipment_id) REFERENCES equipment(id)) ENGINE=InnoDB;
CREATE TABLE downtime_event(id BIGINT AUTO_INCREMENT PRIMARY KEY,equipment_id BIGINT NOT NULL,started_at DATETIME(3) NOT NULL,ended_at DATETIME(3),duration_seconds INT,automatic_reason VARCHAR(100),corrected_reason VARCHAR(100),corrected_by BIGINT,corrected_at DATETIME(3),estimated_loss_quantity DECIMAL(12,2) DEFAULT 0,created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),INDEX(equipment_id,started_at),FOREIGN KEY(equipment_id) REFERENCES equipment(id)) ENGINE=InnoDB;
CREATE TABLE maintenance_history(id BIGINT AUTO_INCREMENT PRIMARY KEY,equipment_id BIGINT NOT NULL,maintenance_type VARCHAR(30),scheduled_at DATETIME(3),performed_at DATETIME(3),action_details TEXT,parts_replaced TEXT,technician VARCHAR(100),next_inspection_at DATETIME(3),created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),FOREIGN KEY(equipment_id) REFERENCES equipment(id)) ENGINE=InnoDB;
CREATE TABLE hourly_production_summary(id BIGINT AUTO_INCREMENT PRIMARY KEY,line_id BIGINT NOT NULL,product_id BIGINT,summary_hour DATETIME(3) NOT NULL,target_quantity INT,production_quantity INT,good_quantity INT,bad_quantity INT,actual_runtime_seconds INT,planned_runtime_seconds INT,downtime_seconds INT,estimated_loss_quantity DECIMAL(12,2),average_cycle_time DECIMAL(10,3),uptime_rate DECIMAL(6,2),created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),UNIQUE(line_id,summary_hour),FOREIGN KEY(line_id) REFERENCES production_line(id),FOREIGN KEY(product_id) REFERENCES product(id)) ENGINE=InnoDB;
CREATE TABLE daily_production_summary LIKE hourly_production_summary;
ALTER TABLE daily_production_summary CHANGE summary_hour summary_date DATE NOT NULL, DROP INDEX line_id, ADD UNIQUE KEY uk_daily(line_id,summary_date);
CREATE TABLE collection_health(equipment_id BIGINT PRIMARY KEY,last_received_at DATETIME(3),last_good_received_at DATETIME(3),success_rate DECIMAL(6,3),consecutive_failures INT DEFAULT 0,average_response_ms INT,missing_count BIGINT DEFAULT 0,reconnect_count INT DEFAULT 0,data_quality ENUM('GOOD','UNCERTAIN','BAD'),updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),FOREIGN KEY(equipment_id) REFERENCES equipment(id)) ENGINE=InnoDB;
CREATE TABLE report_history(id BIGINT AUTO_INCREMENT PRIMARY KEY,report_type VARCHAR(30),file_path VARCHAR(255),status VARCHAR(20),generated_at DATETIME(3),created_by BIGINT,created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)) ENGINE=InnoDB;
CREATE TABLE system_user(id BIGINT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(60) NOT NULL UNIQUE,full_name VARCHAR(100) NOT NULL,password_hash VARCHAR(100) NOT NULL,approval_status VARCHAR(20) NOT NULL,is_locked BOOLEAN DEFAULT FALSE,is_active BOOLEAN DEFAULT TRUE,failed_login_count INT DEFAULT 0,last_login_at DATETIME(3),created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)) ENGINE=InnoDB;
CREATE TABLE user_registration_request(id BIGINT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(60) NOT NULL,full_name VARCHAR(100) NOT NULL,password_hash VARCHAR(100) NOT NULL,factory_id BIGINT,department VARCHAR(100),position VARCHAR(100),phone VARCHAR(30),email VARCHAR(150),requested_role VARCHAR(40),status VARCHAR(20) NOT NULL,reviewed_by BIGINT,reviewed_at DATETIME(3),created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),FOREIGN KEY(factory_id) REFERENCES factory(id)) ENGINE=InnoDB;
CREATE TABLE role(id BIGINT AUTO_INCREMENT PRIMARY KEY,role_code VARCHAR(40) NOT NULL UNIQUE,role_name VARCHAR(100) NOT NULL,created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)) ENGINE=InnoDB;
CREATE TABLE permission(id BIGINT AUTO_INCREMENT PRIMARY KEY,permission_code VARCHAR(80) NOT NULL UNIQUE,permission_name VARCHAR(100),created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)) ENGINE=InnoDB;
CREATE TABLE user_role(user_id BIGINT NOT NULL,role_id BIGINT NOT NULL,PRIMARY KEY(user_id,role_id),FOREIGN KEY(user_id) REFERENCES system_user(id),FOREIGN KEY(role_id) REFERENCES role(id)) ENGINE=InnoDB;
CREATE TABLE role_permission(role_id BIGINT NOT NULL,permission_id BIGINT NOT NULL,PRIMARY KEY(role_id,permission_id),FOREIGN KEY(role_id) REFERENCES role(id),FOREIGN KEY(permission_id) REFERENCES permission(id)) ENGINE=InnoDB;
CREATE TABLE audit_log(id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT,function_name VARCHAR(100),action_name VARCHAR(50),target_type VARCHAR(50),target_id VARCHAR(80),before_value JSON,after_value JSON,ip_address VARCHAR(45),occurred_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),INDEX(user_id,occurred_at),FOREIGN KEY(user_id) REFERENCES system_user(id)) ENGINE=InnoDB;
CREATE TABLE robot_axis_telemetry(id BIGINT AUTO_INCREMENT PRIMARY KEY,robot_telemetry_id BIGINT NOT NULL,axis_number INT NOT NULL,position_value DECIMAL(12,4),speed_value DECIMAL(12,4),load_value DECIMAL(8,3),FOREIGN KEY(robot_telemetry_id) REFERENCES robot_telemetry(id)) ENGINE=InnoDB;
CREATE TABLE maintenance_part_history(id BIGINT AUTO_INCREMENT PRIMARY KEY,maintenance_id BIGINT NOT NULL,part_name VARCHAR(100),part_number VARCHAR(80),quantity INT,created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),FOREIGN KEY(maintenance_id) REFERENCES maintenance_history(id)) ENGINE=InnoDB;
CREATE TABLE service_heartbeat(service_name VARCHAR(50) PRIMARY KEY,status VARCHAR(20) NOT NULL,last_heartbeat_at DATETIME(3) NOT NULL,details VARCHAR(255)) ENGINE=InnoDB;
CREATE TABLE system_health_snapshot(id BIGINT AUTO_INCREMENT PRIMARY KEY,captured_at DATETIME(3) NOT NULL,cpu_percent DECIMAL(5,2),memory_percent DECIMAL(5,2),db_used_mb BIGINT,disk_free_percent DECIMAL(5,2)) ENGINE=InnoDB;
CREATE TABLE system_setting(setting_key VARCHAR(80) PRIMARY KEY,setting_value VARCHAR(255),description VARCHAR(255),updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)) ENGINE=InnoDB;
CREATE TABLE system_error_event(id BIGINT AUTO_INCREMENT PRIMARY KEY,service_name VARCHAR(50),error_code VARCHAR(50),message VARCHAR(500),occurred_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),resolved_at DATETIME(3)) ENGINE=InnoDB;
CREATE TABLE backup_history(id BIGINT AUTO_INCREMENT PRIMARY KEY,started_at DATETIME(3),completed_at DATETIME(3),status VARCHAR(20),file_path VARCHAR(255),size_bytes BIGINT,created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)) ENGINE=InnoDB;
INSERT IGNORE INTO factory(id,factory_code,factory_name,location,timezone) VALUES(1,'HWA-01','화성 제1공장','경기도 화성시','Asia/Seoul');
INSERT IGNORE INTO production_line(id,factory_id,line_code,line_name,display_order) VALUES(1,1,'LINE-01','1라인',1),(2,1,'LINE-02','2라인',2),(3,1,'LINE-03','3라인',3);
INSERT IGNORE INTO product(id,product_code,product_name,vehicle_model,customer,specification) VALUES (1,'FP-LH-2401','프론트 패널 LH','PX5','대한자동차','1.2T'),(2,'FP-RH-2402','프론트 패널 RH','PX5','대한자동차','1.2T'),(3,'SM-LH-1820','사이드 멤버 LH','NX4','한빛모터스','1.6T'),(4,'SM-RH-1821','사이드 멤버 RH','NX4','한빛모터스','1.6T'),(5,'BR-A-0712','브래킷 ASSY A','QX','세림오토','2.0T'),(6,'BR-B-0713','브래킷 ASSY B','QX','세림오토','2.0T');
INSERT IGNORE INTO equipment(id,line_id,equipment_code,equipment_name,equipment_type,manufacturer,model,process_order,installed_date) VALUES
(1,1,'P-01','1라인 800톤 프레스','PRESS','SIM','PRESS-800',1,'2022-01-10'),(2,1,'R-01','1라인 로봇 1','ROBOT','FANUC','M-20iA',2,'2022-01-10'),(3,1,'R-02','1라인 로봇 2','ROBOT','HYUNDAI','HH020',3,'2022-01-10'),(4,1,'R-03','1라인 로봇 3','ROBOT','FANUC','M-20iA',4,'2022-01-10'),(5,1,'R-04','1라인 로봇 4','ROBOT','HYUNDAI','HH020',5,'2022-01-10'),
(6,2,'P-02','2라인 600톤 프레스','PRESS','SIM','PRESS-600',1,'2022-02-10'),(7,2,'R-05','2라인 로봇 1','ROBOT','FANUC','M-20iA',2,'2022-02-10'),(8,2,'R-06','2라인 로봇 2','ROBOT','HYUNDAI','HH020',3,'2022-02-10'),(9,2,'R-07','2라인 로봇 3','ROBOT','FANUC','M-20iA',4,'2022-02-10'),(10,2,'R-08','2라인 로봇 4','ROBOT','HYUNDAI','HH020',5,'2022-02-10'),
(11,3,'P-03','3라인 400톤 프레스','PRESS','SIM','PRESS-400',1,'2022-03-10'),(12,3,'R-09','3라인 로봇 1','ROBOT','FANUC','M-20iA',2,'2022-03-10'),(13,3,'R-10','3라인 로봇 2','ROBOT','HYUNDAI','HH020',3,'2022-03-10'),(14,3,'R-11','3라인 로봇 3','ROBOT','FANUC','M-20iA',4,'2022-03-10'),(15,3,'R-12','3라인 로봇 4','ROBOT','HYUNDAI','HH020',5,'2022-03-10');
INSERT IGNORE INTO equipment_connection(equipment_id,protocol,ip_address,port,is_read_only) SELECT id,'SIMULATOR',NULL,NULL,1 FROM equipment;
INSERT IGNORE INTO product_line_standard(product_id,factory_id,line_id,standard_cycle_time,hourly_rate,standard_spm,target_uptime_rate,default_target_quantity,mold_number,process_order,quality_linked) VALUES(1,1,1,11.8,305,5.1,90,2400,'DIE-101',1,1),(4,1,2,14.5,248,4.1,88,2100,'DIE-204',1,0),(5,1,3,16,225,3.75,86,1800,'DIE-309',1,1);
INSERT IGNORE INTO production_plan(id,work_order_number,production_date,factory_id,line_id,product_id,target_quantity,standard_cycle_time,standard_hourly_rate,planned_start_at,planned_end_at,shift_code,planned_minutes,status) VALUES(1,CONCAT('WO-',DATE_FORMAT(CURRENT_DATE,'%Y%m%d'),'-01'),CURRENT_DATE,1,1,1,2400,11.8,305,TIMESTAMP(CURRENT_DATE,'08:00:00'),TIMESTAMP(CURRENT_DATE,'17:00:00'),'DAY',480,'IN_PROGRESS'),(2,CONCAT('WO-',DATE_FORMAT(CURRENT_DATE,'%Y%m%d'),'-02'),CURRENT_DATE,1,2,4,2100,14.5,248,TIMESTAMP(CURRENT_DATE,'08:00:00'),TIMESTAMP(CURRENT_DATE,'17:00:00'),'DAY',480,'IN_PROGRESS'),(3,CONCAT('WO-',DATE_FORMAT(CURRENT_DATE,'%Y%m%d'),'-03'),CURRENT_DATE,1,3,5,1800,16,225,TIMESTAMP(CURRENT_DATE,'08:00:00'),TIMESTAMP(CURRENT_DATE,'17:00:00'),'DAY',480,'IN_PROGRESS');
INSERT IGNORE INTO equipment_current_state(equipment_id,operating_status,communication_status,display_status,status_started_at,production_count,cycle_time,load_rate,current_amp,temperature,current_alarm,response_ms,last_good_received_at,collected_at) SELECT id,CASE WHEN id=9 THEN 'ROBOT_FAULT' WHEN id=10 THEN 'WAITING' WHEN id=12 THEN 'MANUAL' WHEN id=13 THEN 'TEACHING' WHEN id=15 THEN 'PLANNED_STOP' ELSE 'RUNNING' END,CASE WHEN id=14 THEN 'DISCONNECTED' ELSE 'CONNECTED' END,CASE WHEN id=14 THEN 'COMMUNICATION_LOSS' WHEN id=9 THEN 'ROBOT_FAULT' WHEN id=10 THEN 'WAITING' WHEN id=12 THEN 'MANUAL' WHEN id=13 THEN 'TEACHING' WHEN id=15 THEN 'PLANNED_STOP' ELSE 'RUNNING' END,CURRENT_TIMESTAMP(3)-INTERVAL (id*2) MINUTE,1000+id*30,12+id/10,45+id,10+id/5,38+id/4,IF(id=9,'E071 위치 불일치',NULL),20+id,IF(id=14,CURRENT_TIMESTAMP(3)-INTERVAL 7 MINUTE,CURRENT_TIMESTAMP(3)),CURRENT_TIMESTAMP(3) FROM equipment;
INSERT IGNORE INTO collection_health(equipment_id,last_received_at,last_good_received_at,success_rate,consecutive_failures,average_response_ms,missing_count,reconnect_count,data_quality) SELECT id,IF(id=14,CURRENT_TIMESTAMP(3)-INTERVAL 7 MINUTE,CURRENT_TIMESTAMP(3)),IF(id=14,CURRENT_TIMESTAMP(3)-INTERVAL 7 MINUTE,CURRENT_TIMESTAMP(3)),IF(id=14,91.2,99.9),IF(id=14,24,0),20+id,IF(id=14,421,0),IF(id=14,6,0),IF(id=14,'BAD','GOOD') FROM equipment;
INSERT IGNORE INTO alarm_event(equipment_id,alarm_code,alarm_message,occurred_at,cleared_at,duration_seconds,severity,occurrence_count) VALUES(9,'E071','로봇 위치 불일치',CURRENT_TIMESTAMP(3)-INTERVAL 18 MINUTE,NULL,1080,'CRITICAL',4),(5,'W204','서보 부하율 상승',CURRENT_TIMESTAMP(3)-INTERVAL 50 MINUTE,CURRENT_TIMESTAMP(3)-INTERVAL 47 MINUTE,180,'WARNING',5),(8,'E114','소재 감지 지연',CURRENT_TIMESTAMP(3)-INTERVAL 2 HOUR,CURRENT_TIMESTAMP(3)-INTERVAL 109 MINUTE,660,'WARNING',3);
INSERT IGNORE INTO downtime_event(equipment_id,started_at,duration_seconds,automatic_reason,corrected_reason,corrected_at,estimated_loss_quantity) VALUES(9,CURRENT_TIMESTAMP(3)-INTERVAL 18 MINUTE,1080,'ROBOT_FAULT','위치센서 브래킷 이탈',CURRENT_TIMESTAMP(3)-INTERVAL 5 MINUTE,75),(8,CURRENT_TIMESTAMP(3)-INTERVAL 2 HOUR,660,'MATERIAL_WAIT',NULL,NULL,45);
INSERT IGNORE INTO maintenance_history(equipment_id,maintenance_type,scheduled_at,action_details,next_inspection_at) VALUES(5,'PREVENTIVE',CURRENT_TIMESTAMP(3)+INTERVAL 2 DAY,'서보축 윤활 및 정렬 점검',CURRENT_TIMESTAMP(3)+INTERVAL 2 DAY),(11,'PREVENTIVE',CURRENT_TIMESTAMP(3)+INTERVAL 5 DAY,'금형부 점검',CURRENT_TIMESTAMP(3)+INTERVAL 5 DAY);
INSERT IGNORE INTO role(id,role_code,role_name) VALUES(1,'ROLE_EXECUTIVE','대표자'),(2,'ROLE_MANAGER','생산관리자'),(3,'ROLE_ADMIN','시스템 관리자');
INSERT IGNORE INTO permission(id,permission_code,permission_name) VALUES(1,'MONITOR_READ','모니터링 조회'),(2,'MASTER_WRITE','기준정보 관리');
INSERT IGNORE INTO role_permission VALUES(1,1),(2,1),(2,2),(3,1),(3,2);
-- Development only account: admin / password (BCrypt). Never seed this migration in production profile.
INSERT IGNORE INTO system_user(id,username,full_name,password_hash,approval_status,is_locked,is_active) VALUES(1,'admin','개발 관리자','$2a$10$7EqJtq98hPqEX7fNZaFWoO5qYd6wfmD4r0I7jQcKjF7e6kBjMEX2u','APPROVED',0,1);
INSERT IGNORE INTO user_role VALUES(1,3);
INSERT INTO service_heartbeat(service_name,status,last_heartbeat_at,details) VALUES('BACKEND','UP',CURRENT_TIMESTAMP(3),'seed'),('DEVICE_SERVER','UP',CURRENT_TIMESTAMP(3),'simulator'),('MYSQL','UP',CURRENT_TIMESTAMP(3),'community 8.x') ON DUPLICATE KEY UPDATE last_heartbeat_at=VALUES(last_heartbeat_at);
INSERT IGNORE INTO backup_history(started_at,completed_at,status,file_path,size_bytes) VALUES(CURRENT_TIMESTAMP(3)-INTERVAL 8 HOUR,CURRENT_TIMESTAMP(3)-INTERVAL 479 MINUTE,'SUCCESS','/backup/prima_factory_360.sql',1048576);
CREATE TABLE flyway_schema_history(installed_rank INT NOT NULL PRIMARY KEY,version VARCHAR(50),description VARCHAR(200) NOT NULL,type VARCHAR(20) NOT NULL,script VARCHAR(1000) NOT NULL,checksum INT,installed_by VARCHAR(100) NOT NULL,installed_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,execution_time INT NOT NULL,success BOOLEAN NOT NULL);
INSERT INTO flyway_schema_history VALUES(1,'1','baseline schema','SQL','V1__baseline_schema.sql',NULL,'dump',CURRENT_TIMESTAMP,0,1);
