package com.prima.factory.domain;
public enum EquipmentStatus { RUNNING, WAITING, SPEED_LOSS, SHORT_STOP, LONG_WAIT, ROBOT_FAULT, PRESS_FAULT, MATERIAL_WAIT, DOWNSTREAM_WAIT, MANUAL, TEACHING, PLANNED_STOP, SAFETY_STOP, COMMUNICATION_LOSS, UNCLASSIFIED_STOP }
