import {useCallback,useEffect,useState} from 'react';
import {Check,RefreshCw,ShieldCheck,UserCheck,X} from 'lucide-react';
import {authApi} from '../api/authApi';
import {Card,PageHeader} from '../components/Common';
import type {AssignableRole,RegistrationRequest} from '../types/domain';

export function RegistrationApprovalPage(){
 const [items,setItems]=useState<RegistrationRequest[]>([]),[roles,setRoles]=useState<AssignableRole[]>([]),[selectedRoles,setSelectedRoles]=useState<Record<number,string>>({}),[loading,setLoading]=useState(true),[working,setWorking]=useState<number>(),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [requests,availableRoles]=await Promise.all([authApi.pendingRegistrations(),authApi.assignableRoles()]);setItems(requests);setRoles(availableRoles);setSelectedRoles(Object.fromEntries(requests.map(request=>[request.id,availableRoles.find(role=>role.roleName===request.requestedRole)?.roleCode??availableRoles[0]?.roleCode??''])))}catch(e){setError(e instanceof Error?e.message:'가입 신청을 조회하지 못했습니다.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function decide(id:number,action:'approve'|'reject'){if(!window.confirm(action==='approve'?'선택한 권한으로 가입 신청을 승인하시겠습니까?':'이 가입 신청을 반려하시겠습니까?'))return;setWorking(id);setError('');try{if(action==='approve'){const roleCode=selectedRoles[id];if(!roleCode)throw new Error('부여할 권한을 선택해 주세요.');await authApi.approveRegistration(id,roleCode)}else await authApi.rejectRegistration(id);setItems(current=>current.filter(item=>item.id!==id))}catch(e){setError(e instanceof Error?e.message:'가입 신청을 처리하지 못했습니다.')}finally{setWorking(undefined)}}
 return <><PageHeader title="가입 승인 관리" description="시스템 관리자가 가입 신청을 검토하고 실제 부여할 권한을 선택합니다." actions={<button className="secondary-btn" onClick={()=>void load()}><RefreshCw/> 새로고침</button>}/><div className="safety-bar"><ShieldCheck/><b>관리자 전용</b><span>승인 시 선택한 권한으로 사용자 계정이 생성됩니다.</span></div>{error&&<div className="form-error">{error}</div>}<Card><div className="approval-summary"><UserCheck/><div><b>승인 대기 {items.length}건</b><span>신청 권한과 실제 부여 권한을 비교한 후 승인하세요.</span></div></div>{loading?<div className="state-box"><span className="spinner"/>가입 신청을 불러오는 중입니다.</div>:items.length===0?<div className="approval-empty"><Check/><b>처리할 가입 신청이 없습니다.</b><span>새로운 가입 승인 요청이 접수되면 이 화면에 표시됩니다.</span></div>:<div className="responsive-table"><table><thead><tr><th>신청자</th><th>소속</th><th>신청 권한</th><th>부여할 권한</th><th>신청 일시</th><th>처리</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><b>{item.fullName}</b><small>{item.username} · {item.email}</small></td><td>{item.factoryName}<small>{item.department||'-'} · {item.position||'-'}</small></td><td><span className="role-chip requested">{item.requestedRole}</span></td><td><select className="role-select" value={selectedRoles[item.id]??''} onChange={event=>setSelectedRoles(current=>({...current,[item.id]:event.target.value}))}>{roles.map(role=><option key={role.roleCode} value={role.roleCode}>{role.roleName}</option>)}</select></td><td>{new Date(item.createdAt).toLocaleString('ko-KR')}</td><td><div className="approval-actions"><button className="approve-btn" disabled={working===item.id} onClick={()=>void decide(item.id,'approve')}><Check/>승인</button><button className="reject-btn" disabled={working===item.id} onClick={()=>void decide(item.id,'reject')}><X/>반려</button></div></td></tr>)}</tbody></table></div>}</Card></>
}
