import {useCallback,useEffect,useState} from 'react';
import {RefreshCw,Save,ShieldCheck,Users} from 'lucide-react';
import {authApi} from '../api/authApi';
import {Card,PageHeader} from '../components/Common';
import type {AssignableRole,ManagedUser} from '../types/domain';

export function UserAdministrationPage(){
 const [users,setUsers]=useState<ManagedUser[]>([]),[roles,setRoles]=useState<AssignableRole[]>([]),[selected,setSelected]=useState<Record<number,string>>({}),[loading,setLoading]=useState(true),[working,setWorking]=useState<number>(),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [userRows,roleRows]=await Promise.all([authApi.users(),authApi.assignableRoles()]);setUsers(userRows);setRoles(roleRows);setSelected(Object.fromEntries(userRows.map(user=>[user.id,user.roleCode??roleRows[0]?.roleCode??''])))}catch(e){setError(e instanceof Error?e.message:'사용자 목록을 조회하지 못했습니다.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function save(user:ManagedUser){const roleCode=selected[user.id];if(!roleCode)return;setWorking(user.id);setError('');setNotice('');try{await authApi.updateUserRole(user.id,roleCode);const roleName=roles.find(role=>role.roleCode===roleCode)?.roleName;setUsers(current=>current.map(item=>item.id===user.id?{...item,roleCode,roleName}:item));setNotice(`${user.username} 사용자의 권한을 변경했습니다.`)}catch(e){setError(e instanceof Error?e.message:'사용자 권한을 변경하지 못했습니다.')}finally{setWorking(undefined)}}
 return <><PageHeader title="사용자 리스트" description="가입 승인된 사용자 목록을 확인하고 관리자 또는 일반 유저 권한을 변경합니다." actions={<button className="secondary-btn" onClick={()=>void load()}><RefreshCw/> 새로고침</button>}/><div className="safety-bar"><ShieldCheck/><b>관리자 전용</b><span>현재 로그인한 관리자 자신의 권한은 안전을 위해 변경할 수 없습니다.</span></div>{error&&<div className="form-error">{error}</div>}{notice&&<div className="form-success">{notice}</div>}<Card><div className="approval-summary"><Users/><div><b>가입 사용자 {users.length}명</b><span>권한 변경은 즉시 DB에 반영되며 해당 사용자가 다시 로그인하면 적용됩니다.</span></div></div>{loading?<div className="state-box"><span className="spinner"/>사용자 목록을 불러오는 중입니다.</div>:<div className="responsive-table"><table><thead><tr><th>사용자</th><th>계정 상태</th><th>현재 권한</th><th>변경 권한</th><th>가입 일시</th><th>저장</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><b>{user.fullName}</b><small>{user.username}</small></td><td><span className={user.isActive&&!user.isLocked?'good-text':'bad-text'}>{user.isActive&&!user.isLocked?'정상':'잠김/비활성'}</span></td><td><span className="role-chip requested">{user.roleName??'권한 없음'}</span></td><td><select className="role-select" value={selected[user.id]??''} onChange={event=>setSelected(current=>({...current,[user.id]:event.target.value}))}>{roles.map(role=><option key={role.roleCode} value={role.roleCode}>{role.roleName}</option>)}</select></td><td>{new Date(user.createdAt).toLocaleString('ko-KR')}</td><td><button className="approve-btn role-save" disabled={working===user.id||selected[user.id]===user.roleCode} onClick={()=>void save(user)}><Save/>저장</button></td></tr>)}</tbody></table></div>}</Card></>
}
