import {createContext,useContext,useEffect,useState,type ReactNode} from 'react';
export type Language='ko'|'en';
const LanguageContext=createContext<{language:Language;setLanguage:(language:Language)=>void}>({language:'ko',setLanguage:()=>{}});
const en:Record<string,string>={
 '통합 운영 대시보드':'Integrated Operations Dashboard','일간 리포트':'Daily Report','전체 화면':'Fullscreen','대표자 핵심 요약':'Executive Summary','정상 가동':'Running','대기·주의':'Idle / Warning','정지·계획':'Stopped / Planned','고장·알람':'Fault / Alarm','금일 목표수량':'Today Target','금일 생산실적':'Today Output','생산 달성률':'Achievement','현재 시간당 생산':'Current Hourly Output','평균 사이클타임':'Average Cycle Time','금일 비가동':'Today Downtime','추정 생산손실':'Estimated Production Loss','종료 예상실적':'Forecast Output','라인별 생산 현황':'Production by Line','즉시 조치 필요':'Immediate Action','상세':'Details','시간당 생산량':'Hourly Output','반복 알람 TOP 3':'Recurring Alarms TOP 3','운영 모니터링':'OPERATIONS','통합 대시보드':'Dashboard','실시간 현황':'Realtime Status','성과 분석':'ANALYTICS','생산실적 분석':'Production','가동·비가동':'Uptime / Downtime','알람·정비':'Alarms / Maintenance','시스템 관리':'SYSTEM','설비 등록':'Equipment','제품 등록':'Products','데이터 수집':'Data Collection','가입 승인':'Signup Approvals','접속 공장':'Connected Factory','화성 제1공장':'Hwaseong Plant 1','로그아웃':'Logout','실시간 연결 정상':'Realtime connected','마지막 갱신':'Last update','통합 모니터링 시스템에 로그인하세요.':'Sign in to the integrated monitoring system.','아이디':'Username','비밀번호':'Password','로그인 유지':'Keep me signed in','비밀번호 찾기':'Forgot password','로그인':'Sign in','계정이 없으신가요?':'Need an account?','가입 승인 요청':'Request access','회원가입':'Sign up','이름':'Name','비밀번호 확인':'Confirm password','소속 공장':'Factory','부서':'Department','직책':'Position','연락처':'Phone','이메일':'Email','신청 권한':'Requested role','일반 유저':'General User','관리자':'Administrator','사용자 리스트':'User List','가입 승인 관리':'Signup Approvals','새로고침':'Refresh','신청자':'Applicant','소속':'Organization','부여할 권한':'Assigned role','신청 일시':'Requested at','처리':'Action','승인':'Approve','반려':'Reject','가입 사용자':'Registered users','계정 상태':'Account status','현재 권한':'Current role','변경 권한':'New role','가입 일시':'Joined at','저장':'Save','정상':'Active','권한 없음':'No role','마이 페이지':'My Page','모드 변경':'Theme','언어':'Language','라이트 모드':'Light mode','다크 모드':'Dark mode','내 정보 수정':'Edit profile','사용자 아이디':'Username','개인정보 저장':'Save profile','가입 시 입력한 정보를 확인하고 수정합니다.':'Review and update the information entered during signup.','READ ONLY':'READ ONLY','설비 제어 기능 없음':'No equipment controls'
};
const originals=new WeakMap<Text,string>();
function translate(root:Node,language:Language){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node:Node|null;while((node=walker.nextNode())){const text=node as Text;if(!originals.has(text))originals.set(text,text.data);const original=originals.get(text)??text.data;if(language==='ko'){text.data=original;continue}const trimmed=original.trim();if(en[trimmed])text.data=original.replace(trimmed,en[trimmed])}}
export function LanguageProvider({children}:{children:ReactNode}){const [language,setLanguageState]=useState<Language>(()=>(localStorage.getItem('prima-language') as Language)||'ko');function setLanguage(next:Language){localStorage.setItem('prima-language',next);setLanguageState(next)}useEffect(()=>{translate(document.body,language);const observer=new MutationObserver(records=>records.forEach(record=>{if(record.type==='characterData')translate(record.target,language);record.addedNodes.forEach(node=>translate(node,language))}));observer.observe(document.body,{childList:true,characterData:true,subtree:true});return()=>observer.disconnect()},[language]);return <LanguageContext.Provider value={{language,setLanguage}}>{children}</LanguageContext.Provider>}
export const useLanguage=()=>useContext(LanguageContext);
